"""add youtube_url to recipes

Revision ID: 74de32bbf119
Revises: 84e5c5ed83a2
Create Date: 2026-04-25 16:39:13.695206

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "74de32bbf119"
down_revision: Union[str, Sequence[str], None] = "84e5c5ed83a2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("recipes", sa.Column("youtube_url", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("recipes", "youtube_url")
    # ### end Alembic commands ###
