"""add cascade delete to cook_log

Revision ID: 7ed0af7a0c5f
Revises: 74de32bbf119
Create Date: 2026-04-28 15:53:18.279338

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "7ed0af7a0c5f"
down_revision: Union[str, Sequence[str], None] = "74de32bbf119"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("cook_log_recipe_id_fkey"), "cook_log", type_="foreignkey")
    op.create_foreign_key(
        None, "cook_log", "recipes", ["recipe_id"], ["id"], ondelete="CASCADE"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "cook_log", type_="foreignkey")
    op.create_foreign_key(
        op.f("cook_log_recipe_id_fkey"), "cook_log", "recipes", ["recipe_id"], ["id"]
    )
    # ### end Alembic commands ###
