"""add instructions to recipes

Revision ID: a197c32df0d1
Revises: 4f451935d8cf
Create Date: 2026-04-25 15:29:09.862876

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a197c32df0d1"
down_revision: Union[str, Sequence[str], None] = "4f451935d8cf"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("recipes", sa.Column("instructions", sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("recipes", "instructions")
    # ### end Alembic commands ###
