"""drop unit from recipe_ingredients

Revision ID: e261e7c6ad60
Revises: 7ed0af7a0c5f
Create Date: 2026-04-29 16:48:28.072485

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e261e7c6ad60"
down_revision: Union[str, Sequence[str], None] = "7ed0af7a0c5f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("recipe_ingredients", "unit")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "recipe_ingredients",
        sa.Column("unit", sa.VARCHAR(), autoincrement=False, nullable=True),
    )
    # ### end Alembic commands ###
